## Create array in numpy

### 1. Create Array using np.array() method

In [1]:
import numpy as np

In [1]:
l1=[1,2,3,4,5,6]
print(l1)
print(type(l1))

[1, 2, 3, 4, 5, 6]
<class 'list'>


In [3]:
a1=np.array(l1)

In [4]:
print(a1)

[1 2 3 4 5 6]


In [5]:
print(type(a1))

<class 'numpy.ndarray'>


In [6]:
# one more example for creating np array
a2=np.array([34,56,77,22,99])
print(type(a2))
print(a2)

<class 'numpy.ndarray'>
[34 56 77 22 99]


In [25]:
# statistical functions in numpy

arr3=np.array([34,56,77,22,47,19,99])

max_ele=np.max(arr3)
min_ele=np.min(arr3)

print("Max : ",max_ele)
print("Min : ",min_ele)

mean=np.mean(arr3)
med=np.median(arr3)

print("Mean : ",mean)
print("Median : ",med)

std=np.std(arr3)
var=np.var(arr3)

print("Variance : ",var)
print("Standard Deviation : ",std)

Max :  99
Min :  19
Mean :  50.57142857142857
Median :  47.0
Variance :  739.1020408163266
Standard Deviation :  27.186431189406356


In [16]:
# statistical functions in numpy

arr3=np.array([20,20,20,20,20,20,20])

max_ele=np.max(arr3)
min_ele=np.min(arr3)

print("Max : ",max_ele)
print("Min : ",min_ele)

mean=np.mean(arr3)
med=np.median(arr3)

print("Mean : ",mean)
print("Median : ",med)

std=np.std(arr3)
var=np.var(arr3)

print("Variance : ",var)
print("Standard Deviation : ",std)

Max :  20
Min :  20
Mean :  20.0
Median :  20.0
Variance :  0.0
Standard Deviation :  0.0


In [17]:
print(np.ptp(arr3))

0


In [20]:
print(np.average(arr3))

50.57142857142857


In [37]:
arr4=np.array([1,2,3,4,5,6,7,8,9,10])
print(np.min(arr4))
print(np.percentile(arr4,25))
print(np.percentile(arr4,50))
print(np.percentile(arr4,75))
print(np.max(arr4))
print(np.mean(arr4))
print(np.median(arr4))
print(np.var(arr4))
print(np.std(arr4))
print(np.ptp(arr4))

1
3.25
5.5
7.75
10
5.5
5.5
8.25
2.8722813232690143
9


In [41]:
array4=np.array([1,2,3,4.45,6,"str"])
print(array4)
type(array4[1])

['1' '2' '3' '4.45' '6' 'str']


numpy.str_

### 2. Generate Array using linespace

In [43]:
a1=np.linspace(0,90,10)
print(a1)

[ 0. 10. 20. 30. 40. 50. 60. 70. 80. 90.]


In [44]:
a1=np.linspace(start=200,stop=390,num=5,retstep=True)
print(a1)

(array([200. , 247.5, 295. , 342.5, 390. ]), 47.5)


### 3. Generate arrays using arange( )

In [45]:
a1=np.arange(10)
print(a1)

[0 1 2 3 4 5 6 7 8 9]


In [46]:
a2=np.arange(110,120)
print(a2)

[110 111 112 113 114 115 116 117 118 119]


In [48]:
a2=np.arange(110,120,5)
print(a2)

[110 115]


In [49]:


a3=np.arange(start=110,stop=120,step=3)
print(a3)



[110 113 116 119]


In [50]:


a4=np.arange(start=70,stop=50,step=-5)
print(a4)



[70 65 60 55]



### 4. Generate arrays using ones

In [51]:


arr4= np.ones(6)
print(arr4)



[1. 1. 1. 1. 1. 1.]


In [53]:

arr4= np.ones((6,4))
print(arr4)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [55]:
arr4= np.ones((6,14))
print(arr4)
print(arr4.ndim)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
2


### 5. Generate arrays using zeros

In [56]:
arr4= np.zeros(6)
print(arr4)


[0. 0. 0. 0. 0. 0.]


In [57]:
arr4= np.zeros((6,4))
print(arr4)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [58]:
arr4= np.zeros((6,14))
print(arr4)
print(arr4.ndim)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
2


### 6. Generate arrays using random.rand( )

In [59]:


# Create 1D array of 5 random elements between 0 to 1
a10=np.random.rand(5)
print(a10)



[0.52960436 0.31629213 0.23238804 0.40303415 0.24431246]


In [60]:


# Create 2D array of 35 random elements between 0 to 1
a11=np.random.rand(7,5)
print(a11)



[[0.67553376 0.39596746 0.34309626 0.71268127 0.70460901]
 [0.96984887 0.53723175 0.22497217 0.5470412  0.0256217 ]
 [0.89057903 0.76892475 0.08402855 0.02675323 0.92076263]
 [0.00595971 0.1700914  0.95845922 0.55265948 0.21309924]
 [0.75815637 0.06134076 0.33705461 0.85717993 0.6277131 ]
 [0.16961508 0.3010381  0.78955801 0.70780735 0.91866802]
 [0.97553262 0.63316984 0.82117387 0.35842889 0.89197271]]


In [61]:


# Create 2D array of 35 random int elements between 100 to 150
a12=np.random.randint(100,150,(7,5))
print(a12)



[[142 122 103 120 130]
 [131 137 142 123 143]
 [130 146 140 141 115]
 [119 128 121 130 144]
 [124 104 117 111 115]
 [100 136 113 143 132]
 [133 146 133 134 123]]


In [70]:
# Create 1D array of 5 random elements between 0 to 1
a10=np.random.randint(0,100,1)
print(a10)

[43]


In [71]:


a12=np.random.randint(100,150,(2,2))
print(a12)



[[119 145]
 [147 142]]


In [72]:
a12.shape

(2, 2)

In [73]:
a12.size

4

### 7. Generate arrays using logspace( )

In [74]:
a14=np.logspace(start=1,stop=10,num=5,endpoint=True, base=10)
a14

array([1.00000000e+01, 1.77827941e+03, 3.16227766e+05, 5.62341325e+07,
       1.00000000e+10])

### Advantages of Numpy Array over list

#### 1. Speed

In [1]:
import time

In [11]:
# create list and measure the time for list operations
py_list=[i for i in range(1000000)]

start=time.time()
py_list=[i+2 for i in py_list]
stop=time.time()

print(stop-start)

0.10845255851745605


In [12]:
# create array and measure the time for list operations
py_arr=np.array([i for i in range(1000000)])

start=time.time()
py_arr=py_arr+2
stop=time.time()

print(stop-start)

0.001964569091796875


#### 2. Storage Space

In [13]:
import sys

In [16]:
l1=[i for i in range(100)]
len(l1)

print("Total size required to store l1 = ",sys.getsizeof(l1[0])*len(l1))

Total size required to store l1 =  2400


In [17]:
a1=np.arange(100)
print("total space required to store a1 =",a1.itemsize*100)

total space required to store a1 = 800


### Numpy Operations

In [18]:
a1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
a1.shape

(3, 3)

In [21]:
a1.size

9

In [22]:
np.sum(a1)

45

In [23]:
np.sum(a1,axis=0)

array([12, 15, 18])

In [24]:
np.sum(a1,axis=1)

array([ 6, 15, 24])

In [26]:
a2=np.array([[11,12,13],[14,15,16],[17,18,19]])
a2

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [27]:
np.add(a1,a2)

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [29]:
np.subtract(a2,a1)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [30]:
np.multiply(a1,a2)

array([[ 11,  24,  39],
       [ 56,  75,  96],
       [119, 144, 171]])

In [31]:
np.divide(a2,a1)

array([[11.        ,  6.        ,  4.33333333],
       [ 3.5       ,  3.        ,  2.66666667],
       [ 2.42857143,  2.25      ,  2.11111111]])

In [32]:
np.remainder(a2,a1)

array([[0, 0, 1],
       [2, 0, 4],
       [3, 2, 1]])

In [33]:
a3=a1

In [34]:
a3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
a3=np.append(a1,[[10,11,12]],axis=0)
a3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

### How to create scaler in numpy

In [36]:
import numpy as np

In [37]:
a1=np.array([8])

In [38]:
a1

array([8])

In [39]:
type(a1)

numpy.ndarray

In [40]:
scalar_a1=np.asscalar(a1)

<ipython-input-40-f5645744cc6a>:1: DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead
  scalar_a1=np.asscalar(a1)


In [41]:
scalar_a1

8

In [42]:
type(scalar_a1)

int

### How to create vectors using numpy

In [43]:
l1=[1,2,3]

In [44]:
l2=[[10],
   [11],
   [12]]

In [45]:
v1=np.array(l1)

In [46]:
v2=np.array(l2)

In [47]:
v1

array([1, 2, 3])

In [48]:
v2

array([[10],
       [11],
       [12]])

### how to create and work with Matrix

In [49]:
m1=np.matrix('1,2;3,4')

In [50]:
m1

matrix([[1, 2],
        [3, 4]])

In [51]:
type(m1)

numpy.matrix

In [53]:
m1=np.matrix('1,2,3;4,5,6;7,8,9')

In [54]:
m1

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [55]:
m2=np.matrix('11,12,13;14,15,16;17,18,19')

In [56]:
m2

matrix([[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]])

In [57]:
m1

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [58]:
m2

matrix([[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]])

In [59]:
m1.shape

(3, 3)

In [60]:
m2.shape

(3, 3)

In [62]:
type(m1)

numpy.matrix

In [61]:
np.add(m1,m2)

matrix([[12, 14, 16],
        [18, 20, 22],
        [24, 26, 28]])

In [63]:
np.subtract(m1,m2)

matrix([[-10, -10, -10],
        [-10, -10, -10],
        [-10, -10, -10]])

In [67]:
# dot perform matrix multiplication based on maths rules
np.dot(m1,m2)

matrix([[ 90,  96, 102],
        [216, 231, 246],
        [342, 366, 390]])

In [65]:
m1

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [66]:
m2

matrix([[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]])

In [68]:
np.multiply(m1,m2)

matrix([[ 11,  24,  39],
        [ 56,  75,  96],
        [119, 144, 171]])

In [69]:
m3=np.matrix('2')

In [71]:
m3

matrix([[2]])

In [72]:
m4=np.matrix('2,3;4,5')

In [73]:
m3.shape

(1, 1)

In [74]:
m4.shape

(2, 2)

In [75]:
m3

matrix([[2]])

In [76]:
m4

matrix([[2, 3],
        [4, 5]])

In [77]:
#A(m*n) * B (n*p)= C(m*p)

In [78]:
np.dot(m3,m4)

ValueError: shapes (1,1) and (2,2) not aligned: 1 (dim 1) != 2 (dim 0)

In [79]:
np.multiply(m3,m4)

matrix([[ 4,  6],
        [ 8, 10]])

### Linear Algebra

In [83]:
m2

matrix([[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]])

In [84]:
det_m2=np.linalg.det(m2)
det_m2

-2.131628207280298e-14

In [85]:
rank_m1=np.linalg.matrix_rank(m1)
rank_m1

2

In [86]:
rank_m2=np.linalg.matrix_rank(m2)
rank_m2

2

In [88]:
inv_m2=np.linalg.inv(m2)
inv_m2

matrix([[ 1.40737488e+14, -2.81474977e+14,  1.40737488e+14],
        [-2.81474977e+14,  5.62949953e+14, -2.81474977e+14],
        [ 1.40737488e+14, -2.81474977e+14,  1.40737488e+14]])

In [89]:
#A.A^(-1)=I

In [90]:
A=np.matrix('4,3;2,6')

In [91]:
A

matrix([[4, 3],
        [2, 6]])

In [92]:
det_A=np.linalg.det(A)

In [94]:
round(det_A)

18

In [95]:
inv_A=np.linalg.inv(A)
inv_A

matrix([[ 0.33333333, -0.16666667],
        [-0.11111111,  0.22222222]])

## Linear Equations

In [96]:
A=np.matrix('2,-1;3,2')

In [97]:
A

matrix([[ 2, -1],
        [ 3,  2]])

In [98]:
B=np.matrix('-1;9')

In [99]:
B

matrix([[-1],
        [ 9]])

In [100]:
res=np.linalg.solve(A,B)

In [101]:
res

matrix([[1.],
        [3.]])

### Statistical Concepts

In [102]:
data=[23,34,56,77,88,12,99,46,22,83,84,39]

In [103]:
import numpy as np

In [104]:
a1=np.array(data)

In [110]:
print(np.mean(a1))

55.25


In [108]:
print(np.median(a1))

51.0


In [111]:
print(np.std(a1))

28.685434747736814


In [112]:
print(np.var(a1))

822.8541666666666


In [113]:
print(np.average(a1))

55.25


In [114]:
print(np.ptp(a1))

87


In [115]:
q1=np.percentile(data,25,interpolation='midpoint')

In [116]:
q1

28.5

In [117]:
q2=np.percentile(data,50,interpolation='midpoint')
q2

51.0

In [118]:
q3=np.percentile(data,75,interpolation='midpoint')
q3

83.5

In [120]:
IQR=q3-q1
IQR

55.0

### Broadcasting of Array

In [2]:
array1=np.array([11,22,33])

In [3]:
array2=np.array([5])

In [4]:
print(len(array1))

3


In [5]:
print(len(array2))

1


In [6]:
array3=array1*array2
#       11 22 33  * 5 5 5

In [8]:
print(type(array3))
print(len(array3))
print((array3))

<class 'numpy.ndarray'>
3
[ 55 110 165]


### Array Sorting

In [16]:
arr = np.array([3, 2, 0, 1])

In [19]:
print(np.sort(arr,kind="quicksort"))

[0 1 2 3]


In [12]:
arr = np.array(['banana', 'cherry',"pineapple", 'apple'])

print(np.sort(arr)) 

['apple' 'banana' 'cherry' 'pineapple']


In [13]:
arr = np.array([True, False, True])

print(np.sort(arr)) 

[False  True  True]


In [14]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr)) 

[[2 3 4]
 [0 1 5]]


In [21]:
arr = np.array([6, 1, 4, 2, 18, 9, 3, 4, 2, 8, 11])
# Get a sorted copy of numpy array (Descending Order)
arr = np.sort(arr)[::-1]
print('Sorted Array in Descending Order: ', arr)

Sorted Array in Descending Order:  [18 11  9  8  6  4  4  3  2  2  1]


In [22]:
# Create a 2D Numpy array list of list
arr2D = np.array([[8, 7, 1, 2], [3, 2, 3, 1], [29, 32, 11, 9]])

In [23]:
arr2D

array([[ 8,  7,  1,  2],
       [ 3,  2,  3,  1],
       [29, 32, 11,  9]])

In [24]:
# Sort along axis 0 i.e. sort contents of each Column in numpy array
arr2D.sort(axis=0)
print('Sorted Array : ')
print(arr2D)

Sorted Array : 
[[ 3  2  1  1]
 [ 8  7  3  2]
 [29 32 11  9]]


In [25]:
# Sort along axis 1 i.e. sort contents of each row in numpy array
arr2D.sort(axis=1)
print('Sorted Array : ')
print(arr2D)

Sorted Array : 
[[ 1  1  2  3]
 [ 2  3  7  8]
 [ 9 11 29 32]]


In [26]:
def main():
    # Create a Numpy array from list of numbers
    arr = np.array([6, 1, 4, 2, 18, 9, 3, 4, 2, 8, 11])
    print('Original Array : ', arr)
    print('*** Sort a Numpy Array inplace ***')
    # Sort the numpy array inplace
    arr.sort()
    print('Sorted Array : ', arr)
    print('*** Get a Sorted copy of a Numpy Array ***')
    
    
    arr = np.array([6, 1, 4, 2, 18, 9, 3, 4, 2, 8, 11])
    # To Get a sorted copy of numpy array (Ascending Order)
    sortedArr = np.sort(arr)
    print('Sorted Array : ', sortedArr)
    print('Original Array : ', arr)
    
    
    
    print('*** Sort a Numpy Array in Descending Order ***')
    arr = np.array([6, 1, 4, 2, 18, 9, 3, 4, 2, 8, 11])
    # Get a sorted copy of numpy array (Descending Order)
    arr = np.sort(arr)[::-1]
    print('Sorted Array in Descending Order: ', arr)
    
    # Sort Using 'mergesort'
    sortedArr = np.sort(arr, kind='mergesort')
    print('Sorted Array : ', sortedArr)
    
    # Sort Using 'heapsort'
    sortedArr = np.sort(arr, kind='heapsort')
    print('Sorted Array : ', sortedArr)
    print('*** Sorting 2D numpy array along axis ***')
    
    # Create a 2D Numpy array list of list
    arr2D = np.array([[8, 7, 1, 2], [3, 2, 3, 1], [29, 32, 11, 9]])
    print('2D Numpy Array')
    print(arr2D)
    print('*** Sort Contents of each Column in 2D numpy Array | Sorting along axis 0 ***')
    
    # Sort along axis 0 i.e. sort contents of each Column in numpy array
    arr2D.sort(axis=0)
    print('Sorted Array : ')
    print(arr2D)
    print('*** Sort Contents of each Row in 2D numpy Array | Sorting along axis 1 ***')
    
    # Sort along axis 1 i.e. sort contents of each Row in numpy array
    arr2D.sort(axis=1)
    print('Sorted Array : ')
    print(arr2D)

if __name__ == '__main__':
  main()

Original Array :  [ 6  1  4  2 18  9  3  4  2  8 11]
*** Sort a Numpy Array inplace ***
Sorted Array :  [ 1  2  2  3  4  4  6  8  9 11 18]
*** Get a Sorted copy of a Numpy Array ***
Sorted Array :  [ 1  2  2  3  4  4  6  8  9 11 18]
Original Array :  [ 6  1  4  2 18  9  3  4  2  8 11]
*** Sort a Numpy Array in Descending Order ***
Sorted Array in Descending Order:  [18 11  9  8  6  4  4  3  2  2  1]
Sorted Array :  [ 1  2  2  3  4  4  6  8  9 11 18]
Sorted Array :  [ 1  2  2  3  4  4  6  8  9 11 18]
*** Sorting 2D numpy array along axis ***
2D Numpy Array
[[ 8  7  1  2]
 [ 3  2  3  1]
 [29 32 11  9]]
*** Sort Contents of each Column in 2D numpy Array | Sorting along axis 0 ***
Sorted Array : 
[[ 3  2  1  1]
 [ 8  7  3  2]
 [29 32 11  9]]
*** Sort Contents of each Row in 2D numpy Array | Sorting along axis 1 ***
Sorted Array : 
[[ 1  1  2  3]
 [ 2  3  7  8]
 [ 9 11 29 32]]


### Case Study on Numpy

In [27]:
pip show pandas

Name: pandas
Version: 1.3.3
Summary: Powerful data structures for data analysis, time series, and statistics
Home-page: https://pandas.pydata.org
Author: The Pandas Development Team
Author-email: pandas-dev@python.org
License: BSD-3-Clause
Location: /home/bjg/.local/lib/python3.8/site-packages
Requires: numpy, python-dateutil, pytz
Required-by: 
Note: you may need to restart the kernel to use updated packages.


In [49]:
data=np.loadtxt("/home/bjg/Downloads/cric.tsv",skiprows=1)

In [50]:
data

array([[  0., 100.,  78., 342.],
       [  1.,  11.,  62., 191.],
       [  2.,   8.,  85., 252.],
       [  3.,  71.,  24., 307.],
       [  4., 104.,  17., 229.],
       [  5.,  18., 104., 246.],
       [  6.,   8.,  76., 226.],
       [  7.,  86.,  74., 288.],
       [  8.,  12.,  60., 216.],
       [  9.,  25.,  90., 304.],
       [ 10.,  56.,   6., 272.],
       [ 11.,  88.,  69., 302.],
       [ 12., 147.,  65., 312.],
       [ 13., 121., 146., 370.],
       [ 15.,  99., 110., 362.]])

In [53]:
sachinData=data[:,1]

In [54]:
sachinData

array([100.,  11.,   8.,  71., 104.,  18.,   8.,  86.,  12.,  25.,  56.,
        88., 147., 121.,  99.])

In [55]:
dravidData=data[:,2]

In [56]:
dravidData

array([ 78.,  62.,  85.,  24.,  17., 104.,  76.,  74.,  60.,  90.,   6.,
        69.,  65., 146., 110.])

In [57]:
indiaData=data[:,3]

In [58]:
indiaData

array([342., 191., 252., 307., 229., 246., 226., 288., 216., 304., 272.,
       302., 312., 370., 362.])

In [61]:
print(sachinData.mean())
print(np.median(sachinData))

63.6
71.0


In [62]:
print(dravidData.mean())
print(np.median(dravidData))

71.06666666666666
74.0


In [63]:
print(indiaData.mean())
print(np.median(indiaData))

281.26666666666665
288.0


In [66]:
print(np.count_nonzero(sachinData>99))

4


In [67]:
print(np.count_nonzero(dravidData>99))

3


In [68]:
print(np.count_nonzero(indiaData>300))

7


In [69]:
data

array([[  0., 100.,  78., 342.],
       [  1.,  11.,  62., 191.],
       [  2.,   8.,  85., 252.],
       [  3.,  71.,  24., 307.],
       [  4., 104.,  17., 229.],
       [  5.,  18., 104., 246.],
       [  6.,   8.,  76., 226.],
       [  7.,  86.,  74., 288.],
       [  8.,  12.,  60., 216.],
       [  9.,  25.,  90., 304.],
       [ 10.,  56.,   6., 272.],
       [ 11.,  88.,  69., 302.],
       [ 12., 147.,  65., 312.],
       [ 13., 121., 146., 370.],
       [ 15.,  99., 110., 362.]])

In [70]:
score=np.cumsum(sachinData)
np.searchsorted(score,500)

11

In [71]:
score=np.cumsum(dravidData)
np.searchsorted(score,500)

7